### ISSUE TITLE
Fails to compile due to missing files

### ISSUE THREAD

**Issue by bryankeller** [Kemcake/WWDC2015#1]
<unknown>:0: error: no such file or directory: '/Users/Bryan/Downloads/WWDC2015-master 2/RSIntro/RSIntroView.swift'
<unknown>:0: error: no such file or directory: '/Users/Bryan/Downloads/WWDC2015-master 2/RSIntro/RSIntroElement.swift'
<unknown>:0: error: no such file or directory: '/Users/Bryan/Downloads/WWDC2015-master 2/RSIntro/RSIntroTopPage.swift'
<unknown>:0: error: no such file or directory: '/Users/Bryan/Downloads/WWDC2015-master 2/RSIntro/RSIntroPage.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by remstos** [comment]
Wow you scared me a lot! 
Rsintro is installed as a submodule, running `git submodule update` should work

**Comment by bryankeller** [comment]
Ah ok good, I was nervous for you! Thanks for the info. I really like the parallax effect.

**Comment by remstos** [comment]
I'll update the readme. I received an email with "WWDC 2015" as subject, I thought it was from Apple haha 

And Yes, that's actually a good example of what we can do with [RSIntro](https://github.com/Kemcake/RSIntro), a project I'm still working on to be able to create cool intro like Carousel or IFTTT do
